#!/bin/sh


d1=`date -j -f "%Y-%m-%d" "+%s" $1`
d2=`date -j -f "%Y-%m-%d" "+%s" $2`
((diff_sec=(d2+d1)/2))

date -j -r $diff_sec "+%Y-%m-%d" 
#echo - | awk -v SECS=$diff_sec '{printf "%d\n",SECS/(60*60*24)}'
